### PR TITLE
Move fetch from content to background, fixes #91

### LINKED ISSUE #91: GEN-PLAIN and GEN-XSS not inserting into input fields
Using version 0.6, when I click n the owl and select `GEN-PLAIN` or `GEN-XSS`, nothing happens in the browser, but I see a new payload pop up each time in the Tracy web UI.  The `zz` payloads will insert into the input but not the `GEN`.  

I see no errors in the terminal Tracy is running in when I try these inputs, but in the Javascript console in the web tools in Chrome I see `SyntaxError: Unexpected end of JSON input`, then below that `Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost:7777/api/tracy/tracers/generate?tracer_string=GEN-XSS&url=https://www.w3schools.com/html/html_forms.asp with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

### PR DESCRIPTION
**Pull request by bennyncc**

### CODE REVIEW

File: plugin/scripts/highlight.js [hunk 1]
```diff
@@ -205,22 +197,19 @@ const highlight = (function() {
   // sendScreenshot makes the API request to send the screenshot
   // data URI to a tracer with a specific ID.
   async function sendScreenshot(screenshot, id, conf) {
```
Comment (heathj) [inline plugin/scripts/highlight.js]: Now that all configuration is stored in the background page, we don't need `conf`. Can you remove the conf argument here?

File: plugin/scripts/highlight.js [hunk 2]
```diff
@@ -158,28 +158,20 @@ const highlight = (function() {
   // take a screenshot of the surrounding area and attack that to the tracer.
   async function fillGenPayload(elem, tracerString) {
     const conf = await util.get({ restHost: "localhost", restPort: 7777 });
```
Comment (heathj) [inline plugin/scripts/highlight.js]: Remove this line

**Comment by bennyncc** [comment]
> If you can make the following edits, this would be perfect. Also, I didn't ask, but I assume this fixes the bug, right?

Yes, the payload is retrieved and inserted into the page now, no more `CORB` error.
